### ISSUE TITLE
New Welcome Screen GIF FILE 

### ISSUE THREAD

**Issue by fsalam90** [Crymzix/Pretzel#23]
I dont know if this format is applicable but please try. 

![screen gif 3 0](https://cloud.githubusercontent.com/assets/13363614/8892662/a6148a8a-331b-11e5-81d8-4b6ff9804ee3.gif)

**Comment by Crymzix** [comment]
No the format will not work, GIFs are not compatible in Android without some extra work. Could you just send me the image used in the background without the text, i.e. the splash screen image that you sent me before but this time with all the text removed. I could animate the rest programmatically.

**Comment by fsalam90** [comment]
![opening screen july 24th latest 3](https://cloud.githubusercontent.com/assets/13363614/8897733/3973765c-33cf-11e5-9113-d687cbb8fd36.png)

**Comment by Crymzix** [comment]
No, send me this image but without any of the text. You already sent me the circle icon so that's fine. I don't need the background blurred, I can do that myself.  (Plus this one that you sent me doesn't even have the icon centered so it's really of no use to me)
![splash_screen](https://cloud.githubusercontent.com/assets/4514591/8897767/f1add276-33cf-11e5-82e1-7ecec0d8f090.png)

**Comment by fsalam90** [comment]
Do you want me to centre the icon and resend that image?

**Comment by Crymzix** [comment]
No, as I said, send the above image that I attached without any of the included text. You could send me icon as a separate image. I need every animated aspect of the image to be separate in order to animate it.

**Comment by fsalam90** [comment]
cool

**Comment by fsalam90** [comment]
![loginscreen 3](https://cloud.githubusercontent.com/assets/13363614/8897937/33ad1824-33d2-11e5-8f98-0f212fe34f1a.png)

**Comment by fsalam90** [comment]
fixing the main logo...freakin photoshop crashes everytime
