### ISSUE TITLE
Like Button

### ISSUE THREAD

**Issue by fsalam90** [Crymzix/Pretzel#6]
The Like button to be changes to a "smiling Pretzel logo.

![smiling prtzl final 2 0](https://cloud.githubusercontent.com/assets/13363614/8730852/5e159b22-2ba8-11e5-862c-a996e7f6be4c.png)

**Comment by Crymzix** [comment]
In all honesty this icon looks pretty bad in the app. Either include a better icon that has a flatter style, i.e. one that has a uniform color with no shadow or stick with a modified heart icon. I don't understand why we need to change the "Like" icon in the first place. If the reason is that you think it's unoriginal, I suggest you look at every other app that has the "Like" functionality and notice that all of them use a heart icon or a thumbs up icon (Instagram doesn't really "own" the icon). This icon holds no context or meaning to it, and at least the heart icon is universally recognizable.

**Comment by fsalam90** [comment]
I would agree!!! Can we use a "Star" Icon to represent a like?

**Comment by fsalam90** [comment]
the whole point is to somewhat have our own identity....our close competitor also has a heart button.

**Comment by fsalam90** [comment]
Or have our own Logo as a Like button.
